### ISSUE TITLE
[DISCUSS] Release

### ISSUE THREAD

**Issue by gingerbeardman** [otzbergnet/tabCount#17]
I'm happy, your call to release this.

Let's do another extension!

**Comment by gingerbeardman** [comment]
I think you should make a big deal about not requiring any permissions for this to work.

**Comment by otzbergnet** [comment]
Thank you so much, I had to do some work to actually get it into a releasable state. Important lessons :)

a) AppGroup should start with DevGroup ID, e.g. J3PNNM2UXC.tabcount in my case, rather than reverse domain notation (net.otzberg.tabcount)
b) I had at one point, while adding translations, added a target to the Info.plist - but it shouldn't have that

The latter was hard to track down, since it cause three errors ITMS-90261, ITMS-90277, ITMS-90261 a second time

Anyhow, the file now uploaded OK to the store. I will take a bit of time to get everything together, but I will be sure to let you know, once it is there.

Just to mention, I added your name to the Copyright line in the Info.plist, you did so much to make this better and were so instrumental that anything else would be wrong. I hope you don't mind

**Comment by gingerbeardman** [comment]
That's fine with me, happy to be involved!

Next, perhaps I'll resuscitate my Wayback Machine (archive.org) extension. If you think you'd like to be involved in that, I will invite you?

**Comment by otzbergnet** [comment]
So what did the Wayback Machine extension do? Sounds interesting, even if I think I would want to understand a bit more.

**Comment by gingerbeardman** [comment]
[Wayback-Machine.safariextz.zip](https://github.com/otzbergnet/tabCount/files/3835928/Wayback-Machine.safariextz.zip)

USP:
![Screen shot 2019-11-01 at 10 58 44](https://user-images.githubusercontent.com/49612/68668846-03069e80-0541-11ea-9b87-92c3244833f0.png)

Other features
![62803627-d7f45500-bae2-11e9-8648-171b800de0f3](https://user-images.githubusercontent.com/49612/68668855-09951600-0541-11ea-8935-7ff8a4ca35b7.png)

I was looking at the best way to replicate a context menu like this and there doesn't seem to be one?!

**Comment by otzbergnet** [comment]
Hi Matt,

I'll contact you about the Wayback Machine via e-mail.

TabCount was released: https://apps.apple.com/de/app/tab-count/id1487406555?mt=12

I'll add the download badge to the readme.md and move on. The App Store description is not my finest moment, but it can be changed, as you know...

I'll close this one for now then...

**Comment by gingerbeardman** [comment]
Congrats and well done!
