### ISSUE TITLE
Tabs are being closed when I do not want them to be

### ISSUE THREAD

**Issue by gingerbeardman** [otzbergnet/tabCount#23]
My current setup is as below, but tabs are still being closed.

Happy to help debug. It's happened a bunch this weekend.

Thankfully I have been able to recover them using many presses of Cmd+Shift+T

<img width="640" alt="Screen shot 2021-03-08 at 01 17 51" src="https://user-images.githubusercontent.com/49612/110262614-23673180-7fac-11eb-8f34-1df61671ca25.png">

**Comment by otzbergnet** [comment]
Do you have more details please? Did it happen at over 30 tabs?

If you could please provide more details that would be appreciated. 

Claus

**Comment by gingerbeardman** [comment]
Yes, it's happened 4 times so far. It happens almost almost daily at this rate.

- I'm well over 30 tabs
- I am just working, browsing, opening and closing tabs as I go
- I mostly work with the keyboard, the only mouse interaction is for pointing and clicking links on the page
- At some point I notice "where are all my tabs?" and I have to Cmd+Shift+T to recover them all

My feeling is there is a problem and the tab closing code is being run somehow when it shouldn't be.

I am not sure how I feel about the destructive functions this extension has developed. Perhaps they would be better in another extension, and this one simply count tabs (as the original brief).

Right now I cannot trust the extension. 

This seems to be due to a recent change as I never had this problem until recently.

**Comment by gingerbeardman** [comment]
I see that the latest app store update came out 2 days ago, that coincides with when i started seeing this behaviour.

I hope that helps.

As a workaround I have put 300 in each of the focus boxes. Will report back if that stops it happening.

**Comment by gingerbeardman** [comment]
3 times in 1 day!

I'm going have to disable the extension before some serious damage is done.

Still happy to help you solve this.

**Comment by gingerbeardman** [comment]
I'm still open minded that it might not be this extension but something else.

So I've re-enabled the extension.

**Comment by otzbergnet** [comment]
Hi Matt,

I am so sorry for the trouble, but I am not sure why it would be happening :( I did fuck up with my GitHub process earlier, so things aren't great for me right now and I am too tired to properly look at this.

I tried to replicate the issue. As you can tell i have 17 tabs open and I can keep opening tabs. The first one has focus mode disabled. The second one has it on. That's due to some new logic, that prevents the extension from closing tabs, if it is way above the count that was set. In a previous version, if Focus Mode was on and you had set it to 5 (as in this example) it would be super annoying and kill all windows until it hit 5. This is no longer happening for me.

Question, how many windows do you have open? I am trying to understand if that might play into it?

I also tested with two windows open and Focus Mode enabled and it only closed tabs in the second window, once I had hit 5. I am at an utter loss, but if this is a problem, please disable the extension, I honestly don't want you to lose any work. But if those two buttons are off the popup should show "focus mode" off and in that case the function returns early:

if(!shouldAutoClose && !preventNew){
            return
}

So it "shouldn't" be the extension, but I cannot promise you that it isn't.

Greetings

Claus









On Mon, Mar 8, 2021 at 6:51 PM Matt Sephton <notifications@github.com <mailto:notifications@github.com>> wrote:

I'm still open minded that it might not be this extension but something else.

So I've re-enabled the extension.

**Comment by gingerbeardman** [comment]
No worries, it's not important in the bigger picture.

- 2 windows
- 82 tabs

I also wondered if it's the Tab Space extension, which also has a close tab feature. I ruled that has not been updated for 2 months, so I would have noticed before the last two days. Regardless, I have turned off the feature in that extension also.

**Comment by gingerbeardman** [comment]
OK, first: apologies!

I think I have tracked the problem down.

- I recently started using an app that has shortcuts on the Control key
- I also use Tab Space safari extension that has shortcuts on the Control key
- I forgot that Tab Space has shortcuts that close tabs
- The shortcut to close tabs is the same as a shortcut in the new app I am using
- I guess I must be pressing the key when safari has focus
- No problems since disabling shortcuts in Tab Space
- Feature request made on Tab Space repo

Sorry for the false alarm!

🙈

**Comment by otzbergnet** [comment]
Hi Matt,

While I am super sorry for your trouble, I am happy it wasn't me in the end. I looked over the code and just could not figure out what could cause it. I know how bad I am at code, so I totally planned to look at it in a lot of depth this weekend. Happy to know it wasn't me.

Many thanks for confirming this!

Claus
